# Generated by Django 3.2.8 on 2021-10-19 11:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_trainer_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
